cars = read.csv("Cars.csv")
fix(cars)
attach(cars)
names(cars)
fix(cars)
str(cars)
isOneOwner = as.factor(isOneOwner)
str(cars)
names(cars)
pairs(price~color, cars)
pairs(price~trim, cars)
pairs(price~subTrim, cars)
pairs(price~wheelSize)
pairs(price~fuel)
pairs(fuel~price)
pairs(state~region)
fuel = as.factor(fuel)
pairs(price~fuel)
str(cars)

fit = glm(price~., cars)
summary(fit)
plot(state, region)
state = as.factor(state)
plot(state, region)
region = as.factor(region)
plot(state, region)
